version: 2

sources :
  - name: raw
    schema: gz_raw_data
    description : greenweez raw data source
    tables:
      - name : sales #Alias on sales table
        identifier : raw_gz_sales #Name on Bigquery
        description : sales of greenweez
        freshness:
          warn_after: {count : 90, period : day}
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        columns:
          - name: orders_id || '-' || pdt_id
            tests:
            - unique
            - not_null
          - name : date_date
            description : date sales
          - name : orders_id
            description : orders id sales
          - name : pdt_id
            description : products id sales
          - name : revenue
            description : revenue sales
          - name : quantity
            description : quantity sales 

      - name : products #Alias on products table
        identifier : raw_gz_product #Name on Bigquery
        description : products of greenweez
        columns : 
          - name : products_id
            description : products id
            tests : 
              - unique
              - not_null
          - name : purchSE_PRICE
            description : Price purchase
      - name : ship #Alias on ship table
        identifier : raw_gz_ship #Name on Bigquery
        description : ship of greenweez
        columns :
          - name : orders_id
            description : ids orders
            tests : 
              - unique
              - not_null
          - name : shipping_fee
            description : fee of shipping
          - name : shipping_fee_1
            description : fee of shipping (repetition)
          - name : logCost
            description : Costs of logistic
          - name : ship_cost
            description : Cost of shipping
      - name : adwords #Alias on adwords table
        identifier : raw_gz_adwords #Name on Bigquery
        description : adwords campaign results
        columns :
          - name: date_date || '-' || campaign_key
            tests:
            - unique
            - not_null
          - name : date_date
            description : date adwords
          - name : paid_source
            description : paid source adwords
          - name : campaign_key
            description : campaign key adwords
          - name : camPGN_name
            description : campaign name adwords
          - name : ads_cost
            description : costs ads adwords
          - name : impression
            description : nb impression adwords
          - name : click
            description : nb clicks adwords
      - name : bing
        identifier : raw_gz_bing
        columns :
          - name: date_date || '-' || campaign_key
            tests:
            - unique
            - not_null
          - name : date_date
          - name : paid_source
          - name : campaign_key
          - name : camPGN_name
          - name : ads_cost
          - name : impression
          - name : click
      - name : facebook
        identifier : raw_gz_facebook
        columns :
          - name: date_date || '-' || campaign_key
            tests:
            - unique
            - not_null
          - name : date_date
            tests:
            - not_null
          - name : paid_source
          - name : campaign_key
          - name : camPGN_name
          - name : ads_cost
          - name : impression
          - name : click
      - name : criteo
        identifier : raw_gz_criteo
        columns :
          - name: date_date || '-' || campaign_key
            tests:
            - unique
            - not_null
          - name : date_date
          - name : paid_source
          - name : campaign_key
          - name : camPGN_name
          - name : ads_cost
          - name : impression
          - name : click


models :
  - name : campaigns int
    identifier : int_campaigns
    columns :
      - name: date_date || '-' || campaign_key
        tests:
        - unique
        - not_null
      - name : date_date
      - name : paid_source
      - name : campaign_key
      - name : campaign_name
      - name : ads_cost
      - name : impression
      - name : click
  - name : int_campaigns_day
    columns :
      - name: date_date
        description : dates aggregated
        tests : 
          - unique
          - not_null            
      - name : ads_cost
        description : costs of ads
      - name : ads_impression
        description : number of impressions
      - name : ads_clicks
        description : number of clicks
  - name : finance_campaigns_day
    columns :
      - name: date_date
        description : dates aggregated
        tests : 
          - unique
          - not_null            
      - name : ads_margin
        description : margin of ads
      - name : average_basket
        description : average of basket
      - name : operational_margin
        description : operational margin
      - name : ads_cost
        description : costs of ads
      - name : ads_impression
        description : impression of ads
      - name : ads_clicks
        description : number of clicks
